### ISSUE TITLE
List of SVGs

### ISSUE THREAD

**Issue by juanca** [mavenlink/design-system#25]
The design system site should have a section with all the SVGs for easier navigation. I think the SVGs should also have a reasonable ordering, perhaps in buckets of different kinds. 

Mavenlink definitely has some natural categories:

- Story icons: task, deliverable, milestone, issue
- Logos
- ???
- Profit

**Comment by roblevintennis** [comment]
Historically, I think we did this in a Ruby script that essentially globbed those in a very brute force manner. Probably easy to replicate and control with a bit more nuance. Since we don't separate types by directory, we'd likely have to categorize those in the script itself which is a bit unfortunate. Let's contemplate if there's a better way and/or if restructuring with subdirectories would somehow create a lot of backfilling work.

**Comment by juanca** [comment]
https://mavenlink.github.io/design-system/master/#/Components/IconAll
