### ISSUE TITLE
No word wrap on comments

### ISSUE THREAD

**Issue by SoundedSquash** [mavenlink/design-system#408]
When posting a comment on a task or thread, there is no word wrap, or I suppose in this case character wrap, and also no indication that it is cut off. This is an issue because I thought the text was just cut short and had to inspect element to verify I posted it correctly.

I had a long comma separated list with no spaces that extended past the comment area and out in the void. There should be some wrapping capability to make sure it doesn't disappear or an indication that it is not all shown and an option to show it.
![image](https://user-images.githubusercontent.com/20405599/147256727-f77735e1-846f-4f88-84a2-7ae88ae47ac2.png)

**Comment by juanca** [comment]
Hello @SoundedSquash ,

Thanks for the feedback. After some investigation, we see that the issue is reproducible on the Mavenlink dashboard page. 

Unfortunately, those UI widgets are not rendered by the components in this repository. Normally, we would be happy to help on fixing any of the components or stylesheets in this repository. 

Do you mind sending the feedback through the Mavenlink support team? Please provide as much information as possible to help any designated team to reproduce the issue.
